from Thresholding import bersen, globalT
from Color import space_color
from Components import component_detection

import cv2 as cv
import matplotlib.pyplot as plt

if __name__ == "__main__":
    # Lectura de imágenes
    img1 = cv.imread("carretera.jpg",cv.IMREAD_GRAYSCALE)
    img2 = cv.imread("image-cell.png",cv.IMREAD_GRAYSCALE)
    img3 = cv.imread("person_bacteria.jpeg",cv.IMREAD_GRAYSCALE)
    # Umbralizacion adaptativa
    img1B = bersen.BersenThreshold(img1,2,30,147)
    img2B = bersen.BersenThreshold(img2,2,35,250,2)
    img3B = bersen.BersenThreshold(img3,19,35,186)
    img2B = space_color.invert_binary(img2B)
    img1G = globalT.global_thresholding(img1, 150)
    img2G = globalT.global_thresholding(img2, 100)
    img3G = globalT.global_thresholding(img3, 50)
    img2G = space_color.invert_binary(img2G)
    #Deteccion de componentes 
    img1BC = component_detection.conntected_components(img1B)
    img2BC = component_detection.conntected_components(img2B)
    img3BC = component_detection.conntected_components(img3B)
    img1GC = component_detection.conntected_components(img1G)
    img2GC = component_detection.conntected_components(img2G)
    img3GC = component_detection.conntected_components(img3G)

    plt.figure(1,figsize=(8,8))
    plt.subplot(3,4,1)
    plt.imshow(img1,cmap="gray")
    plt.axis("off")
    plt.title("Imagen original")
    plt.subplot(3,4,2)
    plt.axis("off")
    plt.title("Umbralización Bernsen")
    plt.imshow(img1B,cmap="gray")
    plt.subplot(3,4,3)
    plt.axis("off")
    plt.subplot(3,4,5)
    plt.imshow(img2,cmap="gray")
    plt.axis("off")
    plt.title("Imagen original")
    plt.subplot(3,4,6)
    plt.axis("off")
    plt.title("Umbralización Bernsen")
    plt.imshow(img2B,cmap="gray")
    plt.subplot(3,4,6)
    plt.axis("off")
    plt.subplot(3,4,9)
    plt.axis("off")
    plt.imshow(img3,cmap="gray")
    plt.axis("off")
    plt.title("Imagen original")
    plt.subplot(3,4,10)
    plt.imshow(img3B,cmap="gray")
    plt.axis("off")
    plt.title("Umbralización Bernsen")
    plt.figure(2,figsize=(8,8))
    plt.subplot(3,4,1)
    plt.imshow(img1,cmap="gray")
    plt.axis("off")
    plt.title("Imagen original")
    plt.subplot(3,4,2)
    plt.axis("off")
    plt.title("Componentes U. Bernsen")
    plt.imshow(img1BC,cmap="nipy_spectral")
    plt.subplot(3,4,3)
    plt.axis("off")
    plt.subplot(3,4,5)
    plt.imshow(img2,cmap="gray")
    plt.axis("off")
    plt.title("Imagen original")
    plt.subplot(3,4,6)
    plt.axis("off")
    plt.title("Componentes U. Bernsen")
    plt.imshow(img2BC,cmap="nipy_spectral")
    plt.subplot(3,4,6)
    plt.axis("off")
    plt.subplot(3,4,9)
    plt.axis("off")
    plt.imshow(img3,cmap="gray")
    plt.axis("off")
    plt.title("Imagen original")
    plt.subplot(3,4,10)
    plt.imshow(img3BC,cmap="nipy_spectral")
    plt.axis("off")
    plt.title("Componentes U. Bernsen")
    plt.show()
    
    plt.figure(3,figsize=(12, 12))

    plt.subplot(3, 3, 1)
    plt.imshow(img1, cmap='gray')
    plt.title('Imagen Original')
    plt.axis("off")
    plt.subplot(3, 3, 2)
    plt.imshow(img1G, cmap='gray')
    plt.title('Umbral Global')
    plt.axis("off")
    plt.subplot(3, 3, 3)
    plt.imshow(img1GC, cmap='nipy_spectral')
    plt.title('Componentes conectados')
    plt.axis("off")
    plt.subplot(3, 3, 4)
    plt.imshow(img2, cmap='gray')
    plt.title('Imagen Original')
    plt.axis("off")
    plt.subplot(3, 3, 5)
    plt.imshow(img2G, cmap='gray')
    plt.title('Umbral Global')
    plt.axis("off")
    plt.subplot(3, 3, 6)
    plt.imshow(img2GC, cmap='nipy_spectral')
    plt.title('Componentes Conectados')
    plt.axis("off")
    plt.subplot(3, 3, 7)
    plt.imshow(img3, cmap='gray')
    plt.title('Imagen Original')
    plt.axis("off")
    plt.subplot(3, 3, 8)
    plt.imshow(img3G, cmap='gray')
    plt.title('Umbral Global')
    plt.axis("off")
    plt.subplot(3, 3, 9)
    plt.imshow(img3GC, cmap='nipy_spectral')
    plt.title('Componentes Conectados')
    plt.axis("off")
    plt.show()
